$(function(){
	$('.nav-manage').mouseenter(function(){
		$('.list-nav').show();
	});
	$('.nav-manage').mouseleave(function(){
		$('.list-nav').hide();
	});
	$('.list-nav').mouseenter(function(){
		$('.list-nav').show();
	});
	$('.list-nav').mouseleave(function(){
		$('.list-nav').hide();
	});
});
